### ISSUE TITLE
Demo: "Interdimensional Cable TV" - ChatGPT + Stable Diffusion TV set

### ISSUE THREAD

**Issue by ozramos** [MoarHaus/scratchmoar#18]
<table>
<tr>
<td>
<h1>Overview</h1>
<p>Let's recreate the "Interdimensional Cable" from Rick and Morty as a way to iteratively develop everything we need to integrate ChatGPT and Stable Diffusion into Scratch.</p>
<p><b>API substitute:</b>
<ul>
<li><a href="https://www.boredapi.com/">Bored API</a> (instead of ChatGPT)
<li><a href="https://Lexica.art">Lexica.art</a> (instead of Stable Diffusion)
</ul>
</td>
<td><h4>Inspiration: <a href="https://rickandmorty.fandom.com/wiki/Interdimensional_Cable">https://rickandmorty.fandom.com/wiki/Interdimensional_Cable</a></h4><a href="https://rickandmorty.fandom.com/wiki/Interdimensional_Cable"><img src="https://user-images.githubusercontent.com/69949201/227659137-2e997788-78a4-4841-8af5-2b07543d86d3.png"></a></td>
</tr>
</table>

# Progress
![ezgif-3-fd1c670407](https://user-images.githubusercontent.com/69949201/227657236-3ef7865d-b918-471e-8e76-43608b6971e6.gif)
![Screenshot 2023-03-23 174255](https://user-images.githubusercontent.com/69949201/227658879-f5e6638d-dcb2-4a02-a676-602a38b56e2e.png)

# Milestones
```mermaid
graph TD
Prototype --> StableDiffusion --> ChatGPT
style Prototype fill: #660
```

## Prototype
- [x] Generate new Dimension (set of tv shows)
- [x] Generate new Channel (individual show)
- [x] Create basic interactive scene
- [ ] Add buttons to remote to switch channel or TV
- [ ] Add a favorites menu (and load one by default that has actually good results lol)
- [ ] Persist projects into cloud
- [ ] Share links (and announce project)
