### ISSUE TITLE
Let's add Scratch + Notion integration so that we can create and document projects from one plage

### ISSUE THREAD

**Issue by ozramos** [MoarHaus/scratchmoar#3]
# Milestones
- [x] When I add `?extension=http://localhost:8000` to a Scratch Blocks app like TurboWarp.org or Scratchmoar.netlify.app, I am able to load the Scratchmoar extension
- [x] #5
- [x] #6
- [ ] I can authenticate with Notion and sync projects with Notion
- [ ] I can edit the Notion and see changes happen in Scratch in real time
- [ ] Multiple people can edit the same Scratch project at the same time, using Notion as the event bus

**Comment by ozramos** [comment]
Actually the Notion stuff is out of scope for this extension, maybe as a separate one!
